# Data splitting with scikit-learn

## Data

In [12]:
import pandas as pd

# Load the data from GitHub
LINK = "https://raw.githubusercontent.com/kirenz/notebooks/main/data/animals.csv"
df = pd.read_csv(LINK)

In [13]:
df.head()

   id  class animal  fluffiness    weight
0   1  train    cat    0.339568  3.849709
1   2  train    cat    0.932901  4.192175
2   3  train    cat    1.464966  4.980205
3   4  train    cat   -1.754604  2.320577
4   5  train    cat    3.317117  1.430918

In [14]:
df.tail()

    id       class animal  fluffiness    weight
57  58       train    dog    3.079410  4.554753
58  59       train    dog    5.214446  3.748703
59  60  validation    dog    4.290388  5.821982
60  61        test    dog    5.733855  5.124668
61  62       train    dog    3.906308  4.453108

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          62 non-null     int64
 1   class       62 non-null     object
 2   animal      62 non-null     object
 3   fluffiness  62 non-null     float64
 4   weight      62 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.5+ KB

### Exploration

### Data split

In [17]:
# Select features for simple regression
X = df[['fluffiness', 'weight']]

# Create response
y = df["animal"]

In [18]:
from sklearn.model_selection import train_test_split

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
X_train

    fluffiness    weight
13    1.380174  1.840117
33    4.179815  3.753070
34    3.430356  4.952223
3    -1.754604  2.320577
17    3.585817  3.282986
54    3.882068  6.158162
8     0.995827  2.260557
6     4.273422  1.386778
31    0.398024  1.579316
4     3.317117  1.430918
45    4.722867  3.596294
19    1.045106  2.304558
52    5.326376  3.350376
36    4.359747  4.859186
53    3.122050  5.576142
41    6.013522  4.287570
58    5.214446  3.748703
15    1.144630 -0.767645
40    4.757369  6.388427
27    8.456993  7.635590
26    4.124912  2.537013
24    3.474943  5.158844
44    2.896361  5.621756
11    2.293556  4.150632
32    1.119467  3.074966
55    5.961141  6.156696
43    5.838607  4.861056
37    4.168041  4.269412
29    4.731714  4.524579
46    4.001854  3.680375
1     0.932901  4.192175
21    0.776418  1.905204
2     1.464966  4.980205
49    5.571345  6.197441
39    2.929598  3.514171
35    4.109222  5.112932
23    2.137230  3.914428
60    5.733855  5.124668
10    0.710269  2.582885
22    2.659895  0.055917
18    5.169346  0.353512
61    3.906308  4.453108
20    1.074081  0.189298
7     1.779891 -0.443262
42    3.123897  5.926411
14    2.219412  3.736883
28    4.828940  2.258868
51    7.017180  5.047681
38    4.313654  4.875002

# Model

Simple linear regression